### ISSUE TITLE
keep components on one side

### ISSUE THREAD

**Issue by christandlg** [david-we/sisk#19]
e.g. all SMD components on bot. might reduce assembly costs. 

![grafik](https://github.com/user-attachments/assets/b2842470-0749-4007-9489-b50b7210c492)

![grafik](https://github.com/user-attachments/assets/c3cbf5cf-ab66-43b1-aacd-a4e9064689d6)

**Comment by david-we** [comment]
no automatic assembly planed yet, the on/off switch would be on a diffrent place then, which i am not sure would fit with the case i have in mind...
