### ISSUE TITLE
"Value" field should contain part no

### ISSUE THREAD

**Issue by christandlg** [david-we/sisk#20]
part specific text can be put in custom field e.g. "Label" and displayed on silkscreen instead of "Value"

![grafik](https://github.com/user-attachments/assets/404db17d-27d0-4daf-9de0-857db566dcd0)

![grafik](https://github.com/user-attachments/assets/5d5afdc7-6cdc-4b4d-822b-d621e4711bd1)

![grafik](https://github.com/user-attachments/assets/1a69b11a-ae8a-4eff-ad40-809cd72d6ec2)

![grafik](https://github.com/user-attachments/assets/6324cd9c-e69d-49d7-b450-f5d16b7f16d1)

**Comment by david-we** [comment]
done
