### ISSUE TITLE
I2C Pullups

### ISSUE THREAD

**Issue by christandlg** [david-we/sisk#8]
add pullups to I2C SCL and SDA Lines (~2.2k is good). footprints may stay unpolulated if Nano V2or OLED contains pullups. 
![grafik](https://github.com/user-attachments/assets/fe14d9b6-8ec2-4ad6-888b-1c9822759923)

**Comment by david-we** [comment]
nicenano should contain internal pullups, anyway i integrated the pads to be sure.

https://devzone.nordicsemi.com/f/nordic-q-a/68167/internal-pull-up-on-i2c-bus
https://www.reddit.com/r/zmk/comments/160l9ur/help_zmk_nicenano_v2_with_an_i2c_128x32_oled_oled/
